
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
        REDIS_HOST: redis
        REDIS_PORT: 6379

    image: api:latest
    ports:
      - 8080:80

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"